version: '3.7'

services:

  deployment-manager:
    image: docker-activage.satrd.es/deployment-manager:1.0
    ports:
      - 8001:8080
    environment:
      - METADATA_STORAGE_SERVER_URL=http://metadata_storage_server:8081
    networks:
      - activage-network

  component-configurator:
    image: docker-activage.satrd.es/component-configuration:2.0
    environment:
      - CLIENT_ID=Test
      - SIL_URL=http://activage-test-intermw.inter-iot.eu
      - DOCKER=True
    ports:
      - 8002:8080
    networks:
      - activage-network

  maintenance-panel:
    image: docker-activage.satrd.es/maintenance-panel:1.0
    environment:
      - POSTGRES_HOST=maintenance-panel-database
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=activage-maintenance-panel
      - POSTGRES_USER=activage
      - POSTGRES_PASSWORD=activage
    ports:
      - 8003:8080
    networks:
      - activage-network

  update-manager:
    image: docker-activage.satrd.es/update-manager:1.0
    environment:
      - DOCKER_REGISTRY_SERVER_URL=https://docker-activage.satrd.es
      - DOCKER_REGISTRY_USER=activage
      - DOCKER_REGISTRY_PASSWORD=docker.activage
      - STORAGE=POSTGRES
      - POSTGRES_HOST=update-manager-database
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=activage-update-manager
      - POSTGRES_USER=activage
      - POSTGRES_PASSWORD=activage
    ports:
      - 8004:8080
    networks:
      - activage-network

networks:
  activage-network:
    external: true
