version: "3.3"

services:
  reverse-proxy:
    image: nginx:1.15.12-alpine
    ports:
     - target: 80
       published: 80
       protocol: tcp
       mode: host
    volumes:
      - "./sites-conf:/etc/nginx/conf.d"
    networks:
      - proxy-network

networks:
  proxy-network:
    external:
      name: activage-network
