version: '3.3'

services:
  update-manager-database:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=activage
      - POSTGRES_PASSWORD=activage
      - POSTGRES_DB=activage-update-manager
    ports:
      - 5432:5432
    networks:
      - activage-network

networks:
  activage-network:
    external: true
