http:
  port: 8080

admin:
  port: 9876
  host: localhost

apiEndpoints:
  # Authentication
  auth:
    host: '*'
    paths: '/security/auth'
  keycloak:
    host: '*'
    paths: '/auth/*'



  deployment-manager:
    host: '*'
    paths: '/deployment-tools/api/v1/deployments*'

  maintenance-panel:
    host: '*'
    paths: '/deployment-tools/api/v1/records*'

  update-manager:
    host: '*'
    paths: '/deployment-tools/api/v1/registry*'

  component-configurator-platforms:
    host: '*'
    paths: '/deployment-tools/api/v1/platforms*'

  component-configurator-clients:
    host: '*'
    paths: '/deployment-tools/api/v1/clients*'

  component-configurator-devices:
    host: '*'
    paths: '/deployment-tools/api/v1/devices*'

  deployment-tools-frontend:
    host: '*'
    paths: ['/deployment-tools/*','/deployment-tools*']


serviceEndpoints:
  # AUTHENTICATION
  auth:
    url: '${AUTH_SERVER_URL}/realms/${AUTH_SERVER_REALM}/protocol/openid-connect/token'
  keycloak:
    url: '${AUTH_SERVER_URL}/'

  deployment-manager-api:
    url: 'http://deployment-manager:8080/api/v1/deployments'

  maintenance-panel-api:
    url: 'http://maintenance-panel:8080/api/v1/records'

  update-manager-api:
    url: 'http://update-manager:8080/api/v1/registry'

  component-configurator-platforms-api:
    url: 'http://component-configurator:8080/api/v1/platforms'

  component-configurator-clients-api:
    url: 'http://component-configurator:8080/api/v1/clients'

  component-configurator-devices-api:
    url: 'http://component-configurator:8080/api/v1/devices'

  deployment-tools-frontend-api:
    url: 'http://frontend:8080/'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - request-transformer
  - keycloak-protect

pipelines:
  auth:
    apiEndpoints:
      - auth
    policies:
      - request-transformer:
          - action:
              body:
                add:
                  grant_type: "'password'"
                  client_id: "'${CLIENT_ID}'"
                  client_secret: "'${CLIENT_SECRET}'"
      - proxy:
          - action:
              serviceEndpoint: auth
              xfwd: true
              prependPath:  true
              ignorePath:   false
              stripPath:    true

  keycloak:
    apiEndpoints:
      - keycloak
    policies:
      - proxy:
          - action:
              serviceEndpoint: keycloak
              prependPath:  false
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              xfwd: true

  deployment-manager:
    apiEndpoints:
      - deployment-manager
    policies:
      - keycloak-protect:
      - proxy:
          - action:
              serviceEndpoint: deployment-manager-api
              prependPath:  true
              ignorePath:   false
              stripPath:    true

  maintenance-panel:
    apiEndpoints:
      - maintenance-panel
    policies:
      - keycloak-protect:
      - proxy:
          - action:
              serviceEndpoint: maintenance-panel-api
              prependPath:  true
              ignorePath:   false
              stripPath:    true

  update-manager:
    apiEndpoints:
      - update-manager
    policies:
      - keycloak-protect:
      - proxy:
          - action:
              serviceEndpoint: update-manager-api
              prependPath:  true
              ignorePath:   false
              stripPath:    true

  component-configurator-platforms:
    apiEndpoints:
      - component-configurator-platforms
    policies:
      - keycloak-protect:
      - proxy:
          - action:
              serviceEndpoint: component-configurator-platforms-api
              prependPath:  true
              ignorePath:   false
              stripPath:    true

  component-configurator-clients:
    apiEndpoints:
      - component-configurator-clients
    policies:
      - keycloak-protect:
      - proxy:
          - action:
              serviceEndpoint: component-configurator-clients-api
              prependPath:  true
              ignorePath:   false
              stripPath:    true

  component-configurator-devices:
    apiEndpoints:
      - component-configurator-devices
    policies:
      - keycloak-protect:
      - proxy:
          - action:
              serviceEndpoint: component-configurator-devices-api
              prependPath:  true
              ignorePath:   false
              stripPath:    true

  deployment-tools-frontend:
    apiEndpoints:
      - deployment-tools-frontend
    policies:
      - proxy:
          - action:
              serviceEndpoint: deployment-tools-frontend-api
              prependPath:  true
              ignorePath:   false
              stripPath:    true


